In [30]:
import numpy as np

In [31]:
a=np.array([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])
a


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [32]:
a.ndim

3

In [33]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

# Boardcasting  

## (pachadi ko same hunu parxa ani agadi ko ni blank natra one hunu para ani matra mathmatical operation hunca natra hunna)

In [63]:
c=np.array([[1,2,3]])
d=np.array([[4,5,6],[4,5,6],[4,5,6],[4,5,6]])

In [64]:
print(c.shape)
print(d.shape)

(1, 3)
(4, 3)


In [65]:
c+d

array([[5, 7, 9],
       [5, 7, 9],
       [5, 7, 9],
       [5, 7, 9]])

## Where operation

In [67]:
np.where(d%2==0)

(array([0, 0, 1, 1, 2, 2, 3, 3], dtype=int64),
 array([0, 2, 0, 2, 0, 2, 0, 2], dtype=int64))

In [75]:
np.where((d>2) & (d<6))

(array([0, 0, 1, 1, 2, 2, 3, 3], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [76]:
np.sort(c)

array([[1, 2, 3]])