In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='int64')

print(arr)
print(arr.dtype)


[1 2 3 4]
int64


In [17]:
arry = np.array([1, 2, 3, 4,5], dtype='int8')

print(arry)
print(arry.dtype)

[1 2 3 4 5]
int8


# Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.


In [18]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [19]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
