In [5]:
import numpy as np
var_1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
var_2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(type(var_1))
var_3=var_1*var_2
print(var_3)

#OR

print(var_1.dot(var_2))

<class 'numpy.matrix'>
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# Funtions of Matrix in numpy

### 1) Transpose

In [6]:
var=np.matrix([[1,2,3],[4,5,6]])
print(np.transpose(var))

[[1 4]
 [2 5]
 [3 6]]


In [7]:
print(var.T)

[[1 4]
 [2 5]
 [3 6]]


### 2) Swapaxes

In [11]:
print(np.swapaxes(var,0,1))

[[1 4]
 [2 5]
 [3 6]]


### 3) Inverse