In [247]:
import numpy as np

# making one dimention array

In [248]:
a=np.array([1,2,3])
print(a)

[1 2 3]


# making Two dimention array

In [249]:
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


# Why numpy is better than list
### 1) Less memory

In [250]:
import time 
import sys 

In [251]:
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [252]:
D=np.arange(1000)
print(D.size*D.itemsize)

4000


### 2) Fast

In [253]:
SIZE=10

In [254]:
L1=list(range(SIZE))
L2=list(range(SIZE))

In [255]:
print(L1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [256]:
A1=np.arange(SIZE)
A2=np.arange(SIZE)

In [257]:
print(A1)

[0 1 2 3 4 5 6 7 8 9]


In [258]:
start=time.time()
result=[(x,y) for x,y in zip(L1,L2)]

In [259]:
print((time.time()-start)*1000)

15.167713165283203


In [260]:
start=time.time()
result=A1+A2

In [261]:
print((time.time()-start)*1000)

14.931440353393555


### 3) Convenient