In [2]:
import numpy as np

# square root and standard deviation ( np.sqrt(a) , np.std(a))

In [3]:
a=np.array([(1,2,3),(3,4,5)])

In [4]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [5]:
print(np.std(a))

1.2909944487358056


## Addition ,substraction , multiplication and division

In [20]:
b=np.array([(1,2,3),(3,4,5)])
c=np.array([(1,2,4),(7,4,5)])

In [21]:
print(b+c)

[[ 2  4  7]
 [10  8 10]]


In [22]:
print(b-c)

[[ 0  0 -1]
 [-4  0  0]]


In [23]:
print(b*c)

[[ 1  4 12]
 [21 16 25]]


In [24]:
print(b/c)

[[1.         1.         0.75      ]
 [0.42857143 1.         1.        ]]


## Concatinate two array (np.vstack((a,b))

In [26]:
print(np.vstack((a,b)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]


In [27]:
print(np.hstack((a,b)))

[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


# To make all elements in a single ( row c.ravel())

In [33]:
print(c.ravel())

[1 2 4 7 4 5]
