# Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,4])
x=np.where(arr==4)
print(x)

(array([3, 5], dtype=int64),)


## Find the indexes where the values are even:

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


## Search sorted

In [6]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


## Find the indexes where the values 2, 4, and 6 should be inserted:

In [7]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
