# Initializing Different Types of Arrays

In [2]:
import numpy as np

### for making 0 matrix


In [6]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### For making 1 matrix

In [9]:
np.ones((3,5), dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### For making other number matrix

In [11]:
np.full((2,5),99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [19]:
a=([1,2,3])

In [21]:
np.full_like(a,4)

array([4, 4, 4])

### For random matrix

In [22]:
np.random.rand(4,3)

array([[0.01540409, 0.42289281, 0.09742938],
       [0.3965783 , 0.12723002, 0.51750625],
       [0.73702521, 0.87049929, 0.45935221],
       [0.0399338 , 0.05972014, 0.44057148]])