# Generate Random Number
NumPy offers the random module to work with random numbers.

In [3]:
from numpy import random

In [99]:
x = random.randint(100)

print(x)

17


## Generate Random Float

In [96]:

x = random.rand(2,2)

print(x)

[[0.94370942 0.82725901]
 [0.61046074 0.26291569]]


## Generate Random Array

In [104]:
x=random.randint(100, size=(5))

print(x)

[19 99 92 74 22]


In [106]:
x = random.randint(100, size=(2, 4))

print(x)

[[50 98 19 66]
 [83 99 87 66]]


## Generate Random Number From Array


In [107]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 9 9 9 3]
 [5 9 7 5 3]
 [3 5 7 9 5]]
